name: Publish Ruby Gem

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Ruby Gem
        run: |
          gem build vigilant-ruby.gemspec

      - name: Publish Gem
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          RUBY_GEMS_KEY: ${{ secrets.RUBY_GEMS_KEY }}
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: ${RUBY_GEMS_KEY}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem push vigilant-ruby-*.gem
